package com.coherentlogic.wb.client.core.domain;

/**
 * This class contains constant values used in this framework.
 *
 * @todo This needs to go in the utils package.
 *
 * @author <a href="mailto:support@coherentlogic.com">Support</a>
 */
public class Constants {

    public static final String
        ERROR_TBL = "errors",
        WB_ERROR = "wb:error",
        MESSAGE_TBL = "message",
        WB_MESSAGE = "wb:message",
        CATALOG_SOURCES_TBL = "catalog_sources",
        WB_SOURCES = "wb:sources",
        CATALOG_SOURCE_TBL = "catalog_source",
        WB_SOURCE = "wb:source",
        WB_SOURCE_NOTE = "wb:sourceNote",
        WB_SOURCE_ORGANIZATION = "wb:sourceOrganization",
        PAGE = "page",
        PAGES = "pages",
        PER_PAGE = "per_page",
        INCOME_LEVEL = "incomeLevel",
        LENDING_TYPE = "lendingType",
        TOTAL = "total",
        REGION = "region",
        COUNTRIES_TBL = "countries",
        WB_COUNTRIES = "wb:countries",
        COUNTRY_TBL = "country",
        WB_COUNTRY = "wb:country",
        WB_ISO_CODE = "wb:iso2Code",
        WB_NAME = "wb:name",
        WB_DESCRIPTION = "wb:description",
        WB_URL = "wb:url",
        REGION_TBL = "region",
        WB_REGION = "wb:region",
        ADMIN_REGION_TBL = "admin_region",
        WB_ADMIN_REGION = "wb:adminregion",
        INCOME_LEVELS_TBL = "income_levels",
        WB_INCOME_LEVELS = "wb:IncomeLevels",
        INCOME_LEVEL_TBL = "income_level",
        WB_INCOME_LEVEL = "wb:incomeLevel",
        INDICATORS_TBL = "indicators",
        WB_INDICATORS = "wb:indicators",
        INDICATOR_TBL = "indicator",
        WB_INDICATOR = "wb:indicator",
        WB_LENDING_TYPE = "wb:lendingType",
        LENDING_TYPE_TBL = "lending_type",
        WB_LENDING_TYPES = "wb:lendingTypes",
        LENDING_TYPES_TBL = "lending_types",
        WB_CAPITAL_CITY = "wb:capitalCity",
        WB_LONGITUDE = "wb:longitude",
        WB_LATITUDE = "wb:latitude",
        TOPIC_TBL = "topic",
        INDICATOR_TOPIC_TBL = "indicator_topic",
        INDICATOR_TOPICS_TBL = "indicator_topics",
        SOURCE_TBL = "source",
        WB_TOPIC = "wb:topic",
        TOPICS_TBL = "topics",
        WB_TOPICS = "wb:topics",
        WB_VALUE = "wb:value",
        WB_DATA = "wb:data",
        DATA_POINT_TBL = "data_point",
        DATA_POINTS_TBL = "data_points",
        ID = "id",
        KEY = "key",
        METATYPES = "metatypes",
        MRV = "mrv",
        GAP_FILL = "gapFill",
        YES = "yes",
        NO = "no",
        Q = "q",
        M = "m",
        Y = "y",
        FREQUENCY = "frequency",
        COUNTRIES = "countries",
        DATA_POINT_COUNTRY_TBL = "data_point_country",
        SOURCES = "sources",
        SOURCE = "source",
        INCOME_LEVELS = "incomeLevels",
        INDICATORS = "indicators",
        INDICATOR = "indicator",
        DATA_POINT_INDICATOR_TBL = "data_point_indicator",
        LENDING_TYPES = "lendingTypes",
        TOPICS = "topics",
        TOPIC = "topic",
        V2 = "v2",
        DATA_CATALOG = "datacatalog",
        INDICATOR_SOURCE_TBL = "indicator_source",
        WB_DATE = "wb:date",
        WB_DECIMAL = "wb:decimal",
        VALUE = "value",
        // TODO: Note that this variable is also used as a property and hence
        // should be moved (possibly) to the PropertyConstants class.
        NAME = "name",
        DESCRIPTION = "description",
        URL = "url";
}
